apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.bp.service: phpmyadmin
  name: phpmyadmin
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.bp.service: phpmyadmin
status:
  loadBalancer: {}
