apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.bp.service: realtime-database
  name: realtime-database
spec:
  ports:
  - name: "28015"
    port: 28015
    targetPort: 28015
  - name: "8181"
    port: 8181
    targetPort: 8080
  selector:
    io.bp.service: realtime-database
status:
  loadBalancer: {}
