apiVersion: v1
kind: PersistentVolume
metadata:
  name: social-claim3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: ./scripts/wait.sh
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.bp.service: social-claim3
  name: social-claim3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
