apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.bp.service: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.bp.service: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.bp.service: redis
    spec:
      containers:
      - args:
        - redis-server
        - --requirepass
        image: redis:6.0.5-alpine
        name: session
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
